name: Rust lint & test    

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  working-directory: rust

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04

    steps:
      - run: cat $GITHUB_EVENT_PATH

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: working directory
        run: ls -R
        working-directory: ${{env.working-directory}}

      - name: Setup toolchain
        run: |
          rustup default 1.72
          rustup component add clippy
          rustup component add rustfmt

      - name: Run check
        run: cargo check
        working-directory: ${{env.working-directory}}

      - name: Run clippy
        run: cargo clippy --color always --verbose --workspace --all-targets
        working-directory: ${{env.working-directory}}

      - name: Run rustfmt
        run: cargo fmt --all --check --verbose
        working-directory: ${{env.working-directory}}

  test:
    name: Test
    runs-on: ubuntu-22.04

    steps:
      - run: cat $GITHUB_EVENT_PATH

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup toolchain
        run: rustup default 1.72

      - name: Run test
        run: cargo test
        working-directory: ${{env.working-directory}}
