name: Wasm-pack build & publish Node.js package

# 手動実行のみ
on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  working-directory: rust

jobs:
  build:
    name: Build wasm
    runs-on: ubuntu-22.04

    steps:
      # デバッグ用
      - run: cat $GITHUB_EVENT_PATH

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          wasm-pack --version

      - name: Build
        run: |
          echo "npm package root namespace > ${{ github.repository_owner }}"
          wasm-pack build --target web --scope ${{ github.repository_owner }}
          ls -lah pkg
          cat pkg/package.json
        working-directory: rust/hello-wasm

      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: pkg
          path: rust/hello-wasm/pkg
          retention-days: 5

  publish:
    name: Publish Node.js package
    needs: build
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Download build result
        uses: actions/download-artifact@v3
        with:
          name: pkg
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
          registry-url: https://npm.pkg.github.com
          scope: "@${{ github.repository_owner }}"
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
